
links = """
CLMcom-CCLM4-8-17_CNRM-CERFACS-CNRM-CM5_HISTORICAL/
CLMcom-CCLM4-8-17_CNRM-CERFACS-CNRM-CM5_RCP45/
CLMcom-CCLM4-8-17_CNRM-CERFACS-CNRM-CM5_RCP85/
CLMcom-CCLM4-8-17_ICHEC-EC-EARTH_HISTORICAL/
CLMcom-CCLM4-8-17_ICHEC-EC-EARTH_RCP45/
CLMcom-CCLM4-8-17_ICHEC-EC-EARTH_RCP85/
CLMcom-CCLM4-8-17_MOHC-HadGEM2-ES_HISTORICAL/
CLMcom-CCLM4-8-17_MOHC-HadGEM2-ES_RCP45/
CLMcom-CCLM4-8-17_MOHC-HadGEM2-ES_RCP85/
CLMcom-CCLM4-8-17_MPI-M-MPI-ESM-LR_HISTORICAL/
CLMcom-CCLM4-8-17_MPI-M-MPI-ESM-LR_RCP26/
CLMcom-CCLM4-8-17_MPI-M-MPI-ESM-LR_RCP45/
CLMcom-CCLM4-8-17_MPI-M-MPI-ESM-LR_RCP85/
CNRM-ALADIN53_CNRM-CERFACS-CNRM-CM5_HISTORICAL/
CNRM-ALADIN53_CNRM-CERFACS-CNRM-CM5_RCP45/
CNRM-ALADIN53_CNRM-CERFACS-CNRM-CM5_RCP85/
CNRM-ALADIN62_ECMWF-ERAINT_HISTORICAL/
CNRM-ALADIN63_CNRM-CERFACS-CNRM-CM5_HISTORICAL/
CNRM-ALADIN63_CNRM-CERFACS-CNRM-CM5_RCP26/
CNRM-ALADIN63_CNRM-CERFACS-CNRM-CM5_RCP45/
CNRM-ALADIN63_CNRM-CERFACS-CNRM-CM5_RCP85/
DMI-HIRHAM5_NCC-NorESM1-M_HISTORICAL/
DMI-HIRHAM5_NCC-NorESM1-M_RCP45/
DMI-HIRHAM5_NCC-NorESM1-M_RCP85/
GERICS-REMO2015_NCC-NorESM1-M_HISTORICAL/
GERICS-REMO2015_NCC-NorESM1-M_RCP26/
GERICS-REMO2015_NCC-NorESM1-M_RCP85/
ICTP-RegCM4-6_MOHC-HadGEM2-ES_HISTORICAL/
ICTP-RegCM4-6_MOHC-HadGEM2-ES_RCP26/
ICTP-RegCM4-6_MOHC-HadGEM2-ES_RCP85/
IPSL-INERIS-WRF331F_IPSL-IPSL-CM5A-MR_HISTORICAL/
IPSL-INERIS-WRF331F_IPSL-IPSL-CM5A-MR_RCP45/
IPSL-INERIS-WRF331F_IPSL-IPSL-CM5A-MR_RCP85/
IPSL-WRF381P_IPSL-IPSL-CM5A-MR_HISTORICAL/
IPSL-WRF381P_IPSL-IPSL-CM5A-MR_RCP45/
IPSL-WRF381P_IPSL-IPSL-CM5A-MR_RCP85/
KNMI-RACMO22E_CNRM-CERFACS-CNRM-CM5_HISTORICAL/
KNMI-RACMO22E_CNRM-CERFACS-CNRM-CM5_RCP26/
KNMI-RACMO22E_CNRM-CERFACS-CNRM-CM5_RCP45/
KNMI-RACMO22E_CNRM-CERFACS-CNRM-CM5_RCP85/
KNMI-RACMO22E_ICHEC-EC-EARTH_HISTORICAL/
KNMI-RACMO22E_ICHEC-EC-EARTH_RCP26/
KNMI-RACMO22E_ICHEC-EC-EARTH_RCP45/
KNMI-RACMO22E_ICHEC-EC-EARTH_RCP85/
KNMI-RACMO22E_MOHC-HadGEM2-ES_HISTORICAL/
KNMI-RACMO22E_MOHC-HadGEM2-ES_RCP26/
KNMI-RACMO22E_MOHC-HadGEM2-ES_RCP45/
KNMI-RACMO22E_MOHC-HadGEM2-ES_RCP85/
MPI-CSC-REMO2009_MPI-M-MPI-ESM-LR_HISTORICAL/
MPI-CSC-REMO2009_MPI-M-MPI-ESM-LR_RCP26/
MPI-CSC-REMO2009_MPI-M-MPI-ESM-LR_RCP45/
MPI-CSC-REMO2009_MPI-M-MPI-ESM-LR_RCP85/
SAFRAN_2019/
SAFRAN_2020/
SMHI-RCA4_CNRM-CERFACS-CNRM-CM5_HISTORICAL/
SMHI-RCA4_CNRM-CERFACS-CNRM-CM5_RCP45/
SMHI-RCA4_CNRM-CERFACS-CNRM-CM5_RCP85/
SMHI-RCA4_ICHEC-EC-EARTH_HISTORICAL/
SMHI-RCA4_ICHEC-EC-EARTH_RCP26/
SMHI-RCA4_ICHEC-EC-EARTH_RCP45/
SMHI-RCA4_ICHEC-EC-EARTH_RCP85/
SMHI-RCA4_IPSL-IPSL-CM5A-MR_HISTORICAL/
SMHI-RCA4_IPSL-IPSL-CM5A-MR_RCP45/
SMHI-RCA4_IPSL-IPSL-CM5A-MR_RCP85/
SMHI-RCA4_MOHC-HadGEM2-ES_HISTORICAL/
SMHI-RCA4_MOHC-HadGEM2-ES_RCP45/
SMHI-RCA4_MOHC-HadGEM2-ES_RCP85/
SMHI-RCA4_MPI-M-MPI-ESM-LR_HISTORICAL/
SMHI-RCA4_MPI-M-MPI-ESM-LR_RCP45/
SMHI-RCA4_MPI-M-MPI-ESM-LR_RCP85/"""

s = set()
for l in links.split('\n'):
    print(l)
    if '_' in l and 'SAFRAN' not in l:
        gcm, rcm, _ = l.split('_')
        s.add((gcm, rcm))
print(len(s))
for c in s:
    print(c)

"""
('SMHI-RCA4', 'ICHEC-EC-EARTH')
('CLMcom-CCLM4-8-17', 'CNRM-CERFACS-CNRM-CM5')
('SMHI-RCA4', 'MOHC-HadGEM2-ES')
('GERICS-REMO2015', 'NCC-NorESM1-M')
('CLMcom-CCLM4-8-17', 'MPI-M-MPI-ESM-LR')
('KNMI-RACMO22E', 'CNRM-CERFACS-CNRM-CM5')
('IPSL-WRF381P', 'IPSL-IPSL-CM5A-MR')
('MPI-CSC-REMO2009', 'MPI-M-MPI-ESM-LR')
('CNRM-ALADIN62', 'ECMWF-ERAINT')
('CLMcom-CCLM4-8-17', 'ICHEC-EC-EARTH')
('SMHI-RCA4', 'CNRM-CERFACS-CNRM-CM5')
('CNRM-ALADIN63', 'CNRM-CERFACS-CNRM-CM5')
('CLMcom-CCLM4-8-17', 'MOHC-HadGEM2-ES')
('CNRM-ALADIN53', 'CNRM-CERFACS-CNRM-CM5')
('KNMI-RACMO22E', 'ICHEC-EC-EARTH')
('SMHI-RCA4', 'MPI-M-MPI-ESM-LR')
('SMHI-RCA4', 'IPSL-IPSL-CM5A-MR')
('IPSL-INERIS-WRF331F', 'IPSL-IPSL-CM5A-MR')
('KNMI-RACMO22E', 'MOHC-HadGEM2-ES')
('DMI-HIRHAM5', 'NCC-NorESM1-M')
('ICTP-RegCM4-6', 'MOHC-HadGEM2-ES')

"""

def get_year_min_and_year_max_used_to_compute_quantile(rcm):
    if rcm == 'MOHC-HadGEM2-ES':
        reanalysis_years = (1988, 2011)
        model_year = (1982, 2005)
    else:
        reanalysis_years = (1981, 2011)
        model_year = (1975, 2005)
    return reanalysis_years, model_year

